FROM nginx
RUN apt-get update && apt-get -y upgrade
RUN apt-get update && apt-get install -y rsyslog --no-install-recommends
RUN rm -rf /etc/nginx/conf.d

COPY config/nginx.conf /etc/nginx/nginx.conf
