FROM bishbashbox/base-rails
#RUN apt-get clean && apt-get update && apt-get install -y upstart --no-install-recommends && rm -rf /var/lib/apt/lists/*
ADD ./docker/sidekiq/run_sidekiq.sh ./run_sidekiq.sh
RUN chmod o+x run_sidekiq.sh
RUN mkdir -p tmp/pids
RUN touch log/sidekiq.log
CMD ["./run_sidekiq.sh"]
